### ISSUE TITLE
Add an explanation of gradle-wrapper.jar 

### ISSUE THREAD

**Issue by int-ua** [seguri/Lock#10]
As a file without source it looks suspicious at first glance for someone not familiar with Gradle. Adding a short explanation with link to the verification process would've been beneficial.

https://docs.gradle.org/current/userguide/gradle_wrapper.html#wrapper_checksum_verification

**Comment by seguri** [comment]
Thanks for the input. I've added a Github action to avoid malicious code injection and updated the `README.md`.
