### ISSUE TITLE
Lock says it requires access via accessibility services to work

### ISSUE THREAD

**Issue by battlerock** [seguri/Lock#15]
I'm using android 11 Build RQ3A.211001.001.  This had been a problem for a while, normally showing up after charging the phone.  In the past rebooting the phone would fix the problem but now lock will not function unless i give it "accessibility" access to the phone.  I don't know if this is a problem but it didn't need it before and I would think locking the screen wouldn't take special access (but what do i know).  I'm using lock 1.4.1 installed from F-Droid.  I updated from 1.4.0 to see if it fixed the issue.

**Comment by seguri** [comment]
Please see: https://github.com/seguri/Lock#description

**Comment by battlerock** [comment]
This is still an issue.  I'm using android 12 Build SQ3A.220705.003.A1.  I'm using lock 1.4.1 installed from F-Droid.  So in the above description I state it happens after charging the phone (which is true) but android only does its updates when its being charged.  So its actually after system updates have been applied that lock fails.  A reboot of the phone fixes this issue......but its still an issue and in the whole scheme of things its not that big of a deal but it should still be listed as an open issue.

**Comment by seguri** [comment]
I'm sorry to see you're still experiencing issues. Unfortunately, from your messages is hard to understand what's happening. Feel free to provide screenshots of the problems you're facing, and what are your expectations.

**Comment by battlerock** [comment]
I'm sorry for being unclear.
1. Lock operates correctly most of the time.
2. When I charge my phone the android operating system triggers its updates while the phone is connected to power.
3. After that happens "lock" when I attempt to activate it will come back with an error saying it does not have "accessibility" access to the phone.
4. a Reboot of the phone restores correct operation but does not solve the problem.

Something that happens when the android operating system applies updates (and I don't really know what "that" is) leaves "lock" in an inconsistent state of being unresponsive when attempting to activate and triggering it thinking it needs "accessibility" access (which it already has).  I'm not an android programmer or operating system specialist but I am a LINUX system admin so my troubleshooting of the problem is coming from my past experience troubleshooting other LINUX issues.

Since I have not run into this problem with other apps on the phone I am speculating that "lock" is not following some sort of android based protocol for how its supposed to behave when a system update or patch gets applied.

Like I stated its not a great big deal as a reboot fixes it.  Its just annoying.  If you don't have access to an android 11/12 OS to test this on then I see where you may not be able to do much.  If there is something specific I can provide you from my phone that would further your troubleshooting efforts please let me know and I will provide it if I can.  Thanks!

**Comment by seguri** [comment]
I'm quite sure it's not a problem with my app, especially if you tell me you have a Samsung or Chinese smartphone. There's a list of [bad android manufacturers](https://dontkillmyapp.com/) that do not comply with android standards and are famous for implementing toxic battery-related behaviors that sometimes impact also accessibility services.
If you tell me the app works until you connect the charger, that's very probable it's a problem with the android manufacturer.
There might of course be a bug in my app, but its behavior is so simple that it's unlikely there's something wrong with the way I use accessibility services. I'll welcome any PR that could fix any potential bug.

**Comment by battlerock** [comment]
It is a Google Pixel 5 unlocked aka not from a cellular company that adds extra software.  It should be about as stock as you can get.  I figured it was pretty basic since its just putting the lock button on a screen widget. So since you mentioned battery I went in and changed the app settings from "optimized" to "un-restricted" for lock.  We'll see if that has any impact at all.  Thanks for the quick response.

**Comment by battlerock** [comment]
Even after setting its battery allowance to "un-restricted".  I still received the following message after the unit did an update.  See attached screen shot.  
![Lock_Screen_Error](https://user-images.githubusercontent.com/15821868/221261248-72bd8682-203f-4a39-9457-dd11f37bb004.png)
