### ISSUE TITLE
Crash after a while

### ISSUE THREAD

**Issue by pbl987** [seguri/Lock#16]
The app stops to work regularly. See Screenshot.
Also the screen becomes a "screenshot" of the current screen with a border around it.
I tried to make a screenshot, but the file ended up being all black only.

![markup_385](https://user-images.githubusercontent.com/28102804/179425668-68ada254-294f-42f0-8488-4cbe5594442a.png)

**Comment by seguri** [comment]
"After a while" makes me think you have one of those devices that mess with accessibility services. In this case there's nothing that developers can do to fix this. [Here's an example with Dashlane](https://www.guidingtech.com/fix-android-accessibility-settings-turn-off-automatically/) having the same problem. The author is also suggesting some solutions.

**Comment by pbl987** [comment]
The solutions in the link don't apply in Android 12 anymore. I checked for battery optimization, and it is already switched off.
