### ISSUE TITLE
Issue with device wake up

### ISSUE THREAD

**Issue by nida-khan08** [seguri/Lock#17]
Your app does not come up if it was not in foreground...If I close the app and then lock the phone, and then unlock phone your app does not show up.

**Comment by seguri** [comment]
Hi @nida-khan08, the app has no layouts and closes itself automatically. How do you expect it to be in foreground and show up?

**Comment by nida-khan08** [comment]
I am not understanding  exactly what your app does.

**Comment by seguri** [comment]
Please read the [description](https://github.com/seguri/Lock#description) again.

**Comment by nida-khan08** [comment]
okay...Is there any way to unlock android device with our app custom UI(like Pin, Pattern custom UI) not with the system default UI??
Basically I want to create a device lock app like app lock to handle device unlock with custom UI
Any suggestion would be helpful.

**Comment by seguri** [comment]
Unfortunately I don't have any great suggestion for you. If you find an open source launcher that does that, you could check its source code for some hints.

**Comment by nida-khan08** [comment]
Is there any open source launcher you can suggest??
