### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by user6482** [seguri/Lock#18]
Hello!  This is the perfect app for me, I love to lock the screen by tapping a button.  I looked for an open source option and found it.  Congratulations to the developers. 

 I have a suggestion for a future update: the option of a minimalist icon with a black background for those using amoled screen and black wallpaper.  It would be a few pixels less wasting battery.  If someone could do this it would be perfect for my use.  Thanks.  

Note: I don't know if I sent this in the right channel, this is my first time using GitHub.

**Comment by seguri** [comment]
Hello and welcome to GitHub! I'm happy to hear that the app works well for you.
Regarding your request, I'm not sure that the few pixels composing the background of the current launcher icon have any significant impact on battery life. Nonetheless, feel free to open a PR that changes the icon if you feel so.

**Comment by user6482** [comment]
Thanks!

Em 3 de maio de 2023 05:48:21 BRT, Marco Seguri ***@***.***> escreveu:
