### ISSUE TITLE
Unable to uninstall from Android 4.4.2

### ISSUE THREAD

**Issue by themsay** [seguri/Lock#3]
Hi, After installations from f-droid on my old samsung galaxy 4s, running Android version 4.4.2.

I tried to uninstalled but get error message:
 `Error uninstalling %s. Fail to uninstall due to unkown error`.

What can possible be the issue?
Thanks in advance.

**Comment by seguri** [comment]
Hello, did you remove the app from device administrators? Did you read the "uninstalling" section of README?

**Comment by themsay** [comment]
Thanks for pointing that out. I followed README section it uninstalled successfully. Later I installed it back anyway!
