### ISSUE TITLE
Lock as Assistant app

### ISSUE THREAD

**Issue by sphh** [seguri/Lock#4]
Thanks for your `Lock` app. I use it all the time to lock my phone.

At the moment I have to switch to the home screen, where I can tap the `Lock` app to lock my phone. I would love to do it with a double tap onto the home button.

If this app becomes an assistant app, I would be able to set it in `Settings > Apps > Advanced > Default apps > Assist & voice input`.

Do you think, that's possible?

**Comment by seguri** [comment]
Thanks for using it and thanks for this nice idea! I've never done something similar so I'll need to research a little bit. Please share any link that could help me 😃 (I already found [this](https://developer.android.com/training/articles/assistant))

**Comment by sphh** [comment]
Here are two links which might help you:

- "[Homebot](https://play.google.com/store/apps/details?id=com.abast.homebot&hl=en&gl=us) enables you to change the behaviour of the home button on you smartphone".
- The [DuckDuckGo Android App](https://duckduckgo.com/app) can become an assistant app. The source code can be found at [GitHub](https://github.com/duckduckgo/Android). Maybe that can help to figure out how to implement it?

The assistant app can be set in Nougat 7.0 with `Settings > Apps > Configure apps` (the little wheel) `> Assist & voice input > Assist app`.

**Comment by seguri** [comment]
Hi,
I found that adding this to the manifest:
```xml
<intent-filter>
    <action android:name="android.intent.action.ASSIST" />
    <category android:name="android.intent.category.DEFAULT" />
</intent-filter>
```
makes long-press call my activity's `onCreate`. This could be enough for our purposes but I don't understand why `onProvideAssistContent` isn't called.

EDIT: IN the meanwhile, I released version 1.3.0, let me know if it suits you.

**Comment by sphh** [comment]
Thanks @seguri. That's great. I hope it makes it into F-Droid quickly, because I can't wait to test it!

**Comment by sphh** [comment]
Do you know when this app will make its way into F-Droid?

**Comment by seguri** [comment]
I've checked and the build failed. I've never seen this happen, I'm asking on irc

**Comment by seguri** [comment]
Version 1.3.1 is online!

**Comment by sphh** [comment]
Thanks!!!! Works brilliantly!
