### ISSUE TITLE
Fingerprint and face unlock compatibility

### ISSUE THREAD

**Issue by MarcRdC** [seguri/Lock#5]
Fingerprint/face unlock is disabled after locking phone with Lock app, which is quite inconvenient. As a workaround, some apps ([OFF+](https://play.google.com/store/apps/details?id=org.stanwu.smartscreenlockpro), for example) just turn the screen off and disable key events for a few seconds until hardware lock is activated. Would you consider adding this functionality as an option?

**Comment by seguri** [comment]
Hi, I know the black overlay trick; I'm currently more interested to discover how the Huawei's "lock screen" works for Oreo. For sure, any modification to my app is postponed to the end of August when coming back from holidays :)

**Comment by MarcRdC** [comment]
Thank you for your answer. Enjoy your holidays!

**Comment by seguri** [comment]
This is now supported in 1.4.0 when installed on Android 9+ devices.
