### ISSUE TITLE
turn off screen w/o lock?

### ISSUE THREAD

**Issue by travisfw** [seguri/Lock#9]
Would it be possible to have the app turn off the screen without necessarily (according to system settings) immediately locking?

**Comment by seguri** [comment]
Hi Travis, thanks for sharing. Unfortunately I don't think it would be a good feature for an app called _Lock_ ;)

**Comment by pbl987** [comment]
I really would like this feature too. Maybe you can make a second app?

**Comment by seguri** [comment]
Maybe the app already works like that if you disable any security from your phone. I won't try with mine, cause otherwise I'd have to set again the fingerprint of my banking apps.

**Comment by travisfw** [comment]
That's what I tried first. Then I created the ticket. I haven't been using the app since then, though. 🤷🏻

**Comment by pbl987** [comment]
> if you disable any security from your phone

Yes, if i disable security, there is no more lock screen. Obviously that's not what i (and others) want. 

My use case is to keep security on, and sometimes just turn off screen, e.g. when i am at home, so i don't have to unlock for notifications.

It's up to you wether you make another app or not, i just thought that it is a rather simple task, considering the size of the already existent app.
